apiVersion: v1
kind: Pod
metadata:
  name: flipdeal-pod2
  # namespace: projecta
  labels:
    app: packersmovers
spec:
  containers:
    - name: flipdeal
      image: 699475927298.dkr.ecr.us-east-2.amazonaws.com/flipdeal-eks:latest
      ports:
        - containerPort: 8080